/*
 * THIS FILE IS ONLY FOR DEVELOPMENT PURPOSE.
 * IT DOES NOT AFFECT ROUTING SYSTEM, WHICH IS FILE BASED.
 * EVEN SO, KEEP IT UPDATED TO HAVE BETTER DEVELOPMENT EXPERIENCE.
 */

export const HOME_PATH = "/";
